{{- define "quai-blockscout.ingress" }}
- host: {{ if .Values.quaiBlockscout.chain }}prime.{{ .Values.quaiBlockscout.chain }}.quaiscan.io{{ else }}prime.quaiscan.io{{ end }}
  http:
    paths:
    - path: /
      pathType: Prefix
      backend:
        service:
          name: prime-{{ include "quai-blockscout.name" $ }}
          port:
            name: http
{{- end }}
