{{- range $shard := .Values.quaiBlockscout.shards }}
{{ include "quai-blockscout.configmap" $ | replace "prime" $shard.name | replace "<HTTP>" $shard.ports.http | replace "<WS>" $shard.ports.ws | replace "<INDEX>" $shard.index }}
---
{{- end }}
