{{- $name := include "quai-blockscout.name" . -}}
{{- $chain := .Values.quaiBlockscout.chain }}
{{- $host := "" }}
{{ if $chain }}
{{- $host = printf "%s.quaiscan.io" $chain }}
{{ else }}
{{- $host = "quaiscan.io" }}
{{ end }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $name }}
  annotations:
    kubernetes.io/ingress.global-static-ip-name: {{ $name }}
    kubernetes.io/ingress.class: "gce"
    networking.gke.io/managed-certificates: {{ $name }}
    networking.gke.io/v1beta1.FrontendConfig: {{ $name }}
  namespace: {{ .Values.quaiBlockscout.env }}
spec:
  defaultBackend:
    service:
      name: prime-{{ $name }}
      port:
        name: http
  rules:
  - host: {{ $host }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: prime-{{ $name }}
            port:
              name: http
{{- range $shard := .Values.quaiBlockscout.shards }}
{{ if $chain }}
{{- $host = printf "%s.%s.quaiscan.io" $shard.name $chain }}
{{ else }}
{{- $host = printf "%s.quaiscan.io" $shard.name }}
{{ end }}
{{ include "quai-blockscout.ingress" $ | replace "<HOST>" $host | replace "prime" $shard.name | indent 2 }}
{{- end }}
